services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wms-laravel
    container_name: wms-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - wms-laravel
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: wms-laravel-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wms-laravel

  db:
    image: mysql:8.0
    container_name: wms-laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wms
      MYSQL_USER: huiden
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - wms-laravel

networks:
  wms-laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local