services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wms-laravel-image
    container_name: wms-laravel
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - wms-laravel
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: wms-laravel-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wms-laravel

networks:
  wms-laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local