version: '3'

services:
  # App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wms-laravel
    user: root
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - wms-laravel
    extra_hosts:
      - "host.docker.internal:168.168.1.25"

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: wms-laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wms-laravel

networks:
  wms-laravel:
    driver: bridge